// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: platformer.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Platformer {
  public static partial class Platformer
  {
    static readonly string __ServiceName = "platformer.Platformer";

    static readonly grpc::Marshaller<global::Platformer.CreateRoomRequest> __Marshaller_platformer_CreateRoomRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Platformer.CreateRoomRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Platformer.CreateRoomResponse> __Marshaller_platformer_CreateRoomResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Platformer.CreateRoomResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Platformer.JoinRoomRequest> __Marshaller_platformer_JoinRoomRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Platformer.JoinRoomRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Platformer.JoinRoomResponse> __Marshaller_platformer_JoinRoomResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Platformer.JoinRoomResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Platformer.CreateRoomRequest, global::Platformer.CreateRoomResponse> __Method_CreateRoom = new grpc::Method<global::Platformer.CreateRoomRequest, global::Platformer.CreateRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateRoom",
        __Marshaller_platformer_CreateRoomRequest,
        __Marshaller_platformer_CreateRoomResponse);

    static readonly grpc::Method<global::Platformer.JoinRoomRequest, global::Platformer.JoinRoomResponse> __Method_JoinRoom = new grpc::Method<global::Platformer.JoinRoomRequest, global::Platformer.JoinRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "JoinRoom",
        __Marshaller_platformer_JoinRoomRequest,
        __Marshaller_platformer_JoinRoomResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Platformer.PlatformerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Platformer</summary>
    public abstract partial class PlatformerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Platformer.CreateRoomResponse> CreateRoom(global::Platformer.CreateRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// rpc SyncPosition(stream PositionById) returns (stream PositionById);
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Platformer.JoinRoomResponse> JoinRoom(global::Platformer.JoinRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Platformer</summary>
    public partial class PlatformerClient : grpc::ClientBase<PlatformerClient>
    {
      /// <summary>Creates a new client for Platformer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PlatformerClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Platformer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PlatformerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PlatformerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PlatformerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Platformer.CreateRoomResponse CreateRoom(global::Platformer.CreateRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRoom(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Platformer.CreateRoomResponse CreateRoom(global::Platformer.CreateRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateRoom, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Platformer.CreateRoomResponse> CreateRoomAsync(global::Platformer.CreateRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateRoomAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Platformer.CreateRoomResponse> CreateRoomAsync(global::Platformer.CreateRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateRoom, null, options, request);
      }
      /// <summary>
      /// rpc SyncPosition(stream PositionById) returns (stream PositionById);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Platformer.JoinRoomResponse JoinRoom(global::Platformer.JoinRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return JoinRoom(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// rpc SyncPosition(stream PositionById) returns (stream PositionById);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Platformer.JoinRoomResponse JoinRoom(global::Platformer.JoinRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_JoinRoom, null, options, request);
      }
      /// <summary>
      /// rpc SyncPosition(stream PositionById) returns (stream PositionById);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Platformer.JoinRoomResponse> JoinRoomAsync(global::Platformer.JoinRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return JoinRoomAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// rpc SyncPosition(stream PositionById) returns (stream PositionById);
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Platformer.JoinRoomResponse> JoinRoomAsync(global::Platformer.JoinRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_JoinRoom, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PlatformerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PlatformerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PlatformerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateRoom, serviceImpl.CreateRoom)
          .AddMethod(__Method_JoinRoom, serviceImpl.JoinRoom).Build();
    }

  }
}
#endregion
