// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platformer.proto

package platformer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed0ab0be00c75b7, []int{0}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

type CreateRoomResponse struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed0ab0be00c75b7, []int{1}
}

func (m *CreateRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponse.Unmarshal(m, b)
}
func (m *CreateRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponse.Merge(m, src)
}
func (m *CreateRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponse.Size(m)
}
func (m *CreateRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponse proto.InternalMessageInfo

func (m *CreateRoomResponse) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type JoinRoomRequest struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed0ab0be00c75b7, []int{2}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type JoinRoomResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed0ab0be00c75b7, []int{3}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed0ab0be00c75b7, []int{4}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type PositionById struct {
	Id                   int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PositionById) Reset()         { *m = PositionById{} }
func (m *PositionById) String() string { return proto.CompactTextString(m) }
func (*PositionById) ProtoMessage()    {}
func (*PositionById) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed0ab0be00c75b7, []int{5}
}

func (m *PositionById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionById.Unmarshal(m, b)
}
func (m *PositionById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionById.Marshal(b, m, deterministic)
}
func (m *PositionById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionById.Merge(m, src)
}
func (m *PositionById) XXX_Size() int {
	return xxx_messageInfo_PositionById.Size(m)
}
func (m *PositionById) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionById.DiscardUnknown(m)
}

var xxx_messageInfo_PositionById proto.InternalMessageInfo

func (m *PositionById) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PositionById) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "platformer.CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "platformer.CreateRoomResponse")
	proto.RegisterType((*JoinRoomRequest)(nil), "platformer.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "platformer.JoinRoomResponse")
	proto.RegisterType((*Position)(nil), "platformer.Position")
	proto.RegisterType((*PositionById)(nil), "platformer.PositionById")
}

func init() { proto.RegisterFile("platformer.proto", fileDescriptor_7ed0ab0be00c75b7) }

var fileDescriptor_7ed0ab0be00c75b7 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdf, 0x4a, 0xf3, 0x40,
	0x10, 0xc5, 0xd9, 0xc0, 0xd7, 0x2f, 0x8e, 0x41, 0xeb, 0x2a, 0x58, 0xa2, 0x15, 0xd9, 0x0b, 0xe9,
	0x8d, 0xa5, 0xd6, 0x37, 0xb0, 0x28, 0x44, 0x6f, 0x42, 0xfa, 0x00, 0xa5, 0x26, 0x2b, 0x2c, 0x98,
	0x4c, 0xdc, 0x49, 0xa0, 0x79, 0x63, 0x1f, 0x43, 0x36, 0xdd, 0xfc, 0x41, 0x9b, 0xcb, 0x99, 0x73,
	0xe6, 0xcc, 0xce, 0x8f, 0x85, 0x71, 0xfe, 0xb9, 0x2d, 0x3e, 0x50, 0xa7, 0x52, 0xcf, 0x73, 0x8d,
	0x05, 0x72, 0xe8, 0x3a, 0xe2, 0x1c, 0xce, 0x56, 0x5a, 0x6e, 0x0b, 0x19, 0x21, 0xa6, 0x91, 0xfc,
	0x2a, 0x25, 0x15, 0xe2, 0x1e, 0x78, 0xbf, 0x49, 0x39, 0x66, 0x24, 0xf9, 0x25, 0xfc, 0xd7, 0x88,
	0xe9, 0x46, 0x25, 0x13, 0x76, 0xcb, 0x66, 0xff, 0xa2, 0x91, 0x29, 0x83, 0x44, 0xac, 0xe0, 0xf4,
	0x15, 0x55, 0xd6, 0x4b, 0x18, 0xf4, 0x1a, 0xa1, 0x24, 0xa9, 0x8d, 0xe0, 0xec, 0x05, 0x53, 0x06,
	0x89, 0x78, 0x80, 0x71, 0x17, 0x62, 0x37, 0x4e, 0x01, 0x14, 0x6d, 0xa8, 0x8c, 0x63, 0x49, 0x54,
	0x07, 0xb9, 0xd1, 0x91, 0xa2, 0xf5, 0xbe, 0x21, 0xee, 0xc0, 0x0d, 0x91, 0x54, 0xa1, 0x30, 0xe3,
	0x1e, 0xb0, 0x9d, 0x5d, 0xc5, 0x76, 0xa6, 0xaa, 0x6c, 0x3e, 0xab, 0x44, 0x08, 0x5e, 0xe3, 0x7b,
	0xaa, 0x82, 0x84, 0x9f, 0x80, 0xd3, 0xbe, 0xcb, 0x51, 0x09, 0x5f, 0x80, 0x9b, 0x5b, 0xbd, 0x1e,
	0x3a, 0x5e, 0x5e, 0xcc, 0x7b, 0xd0, 0x9a, 0xd9, 0xa8, 0x75, 0x2d, 0xbf, 0x19, 0x40, 0xd8, 0x3a,
	0xf8, 0x1b, 0x40, 0xc7, 0x8b, 0x4f, 0xfb, 0xc3, 0x7f, 0xe0, 0xfa, 0x37, 0x43, 0xb2, 0x3d, 0xfa,
	0x19, 0xdc, 0x06, 0x04, 0xbf, 0xea, 0x7b, 0x7f, 0x31, 0xf6, 0xaf, 0x0f, 0x8b, 0x36, 0xe6, 0x05,
	0xbc, 0x75, 0x95, 0xc5, 0x2d, 0xa0, 0xc9, 0xa1, 0x93, 0x0c, 0x0e, 0x7f, 0x50, 0x99, 0xb1, 0x05,
	0x7b, 0x1f, 0xd5, 0x7f, 0xe6, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xbf, 0x88, 0x96, 0x47,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlatformerClient is the client API for Platformer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlatformerClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
	SyncPosition(ctx context.Context, opts ...grpc.CallOption) (Platformer_SyncPositionClient, error)
}

type platformerClient struct {
	cc *grpc.ClientConn
}

func NewPlatformerClient(cc *grpc.ClientConn) PlatformerClient {
	return &platformerClient{cc}
}

func (c *platformerClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, "/platformer.Platformer/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformerClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, "/platformer.Platformer/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformerClient) SyncPosition(ctx context.Context, opts ...grpc.CallOption) (Platformer_SyncPositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Platformer_serviceDesc.Streams[0], "/platformer.Platformer/SyncPosition", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformerSyncPositionClient{stream}
	return x, nil
}

type Platformer_SyncPositionClient interface {
	Send(*PositionById) error
	Recv() (*PositionById, error)
	grpc.ClientStream
}

type platformerSyncPositionClient struct {
	grpc.ClientStream
}

func (x *platformerSyncPositionClient) Send(m *PositionById) error {
	return x.ClientStream.SendMsg(m)
}

func (x *platformerSyncPositionClient) Recv() (*PositionById, error) {
	m := new(PositionById)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlatformerServer is the server API for Platformer service.
type PlatformerServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	SyncPosition(Platformer_SyncPositionServer) error
}

func RegisterPlatformerServer(s *grpc.Server, srv PlatformerServer) {
	s.RegisterService(&_Platformer_serviceDesc, srv)
}

func _Platformer_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformerServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platformer.Platformer/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformerServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platformer_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformerServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/platformer.Platformer/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformerServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platformer_SyncPosition_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlatformerServer).SyncPosition(&platformerSyncPositionServer{stream})
}

type Platformer_SyncPositionServer interface {
	Send(*PositionById) error
	Recv() (*PositionById, error)
	grpc.ServerStream
}

type platformerSyncPositionServer struct {
	grpc.ServerStream
}

func (x *platformerSyncPositionServer) Send(m *PositionById) error {
	return x.ServerStream.SendMsg(m)
}

func (x *platformerSyncPositionServer) Recv() (*PositionById, error) {
	m := new(PositionById)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Platformer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "platformer.Platformer",
	HandlerType: (*PlatformerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _Platformer_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _Platformer_JoinRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncPosition",
			Handler:       _Platformer_SyncPosition_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "platformer.proto",
}
